var routesDataJson = JSON.parse(`[
    {
      "route_id": "01",
      "agency_id": "LTC -2020 November",
      "route_short_name": "01",
      "route_long_name": "Route 1",
      "route_desc": "",
      "route_type": 3,
      "route_url": "",
      "route_color": "70C2DA",
      "route_text_color": "000000"
    },
    {
      "route_id": "02",
      "agency_id": "LTC -2020 November",
      "route_short_name": "02",
      "route_long_name": "Route 2",
      "route_desc": "",
      "route_type": 3,
      "route_url": "",
      "route_color": "0080C0",
      "route_text_color": "000000"
    },
    {
      "route_id": "03",
      "agency_id": "LTC -2020 November",
      "route_short_name": "03",
      "route_long_name": "Route 3",
      "route_desc": "",
      "route_type": 3,
      "route_url": "",
      "route_color": "C28585",
      "route_text_color": "000000"
    },
    {
      "route_id": "04",
      "agency_id": "LTC -2020 November",
      "route_short_name": "04",
      "route_long_name": "Route 4",
      "route_desc": "",
      "route_type": 3,
      "route_url": "",
      "route_color": "7373B9",
      "route_text_color": "000000"
    },
    {
      "route_id": "05",
      "agency_id": "LTC -2020 November",
      "route_short_name": "05",
      "route_long_name": "Route 5",
      "route_desc": "",
      "route_type": 3,
      "route_url": "",
      "route_color": "00FF00",
      "route_text_color": "000000"
    },
    {
      "route_id": "06",
      "agency_id": "LTC -2020 November",
      "route_short_name": "06",
      "route_long_name": "Route 6",
      "route_desc": "",
      "route_type": 3,
      "route_url": "",
      "route_color": "008080",
      "route_text_color": "000000"
    },
    {
      "route_id": "07",
      "agency_id": "LTC -2020 November",
      "route_short_name": "07",
      "route_long_name": "Route 7",
      "route_desc": "",
      "route_type": 3,
      "route_url": "",
      "route_color": "9D3CFF",
      "route_text_color": "000000"
    },
    {
      "route_id": "09",
      "agency_id": "LTC -2020 November",
      "route_short_name": "09",
      "route_long_name": "Route 9",
      "route_desc": "",
      "route_type": 3,
      "route_url": "",
      "route_color": "B36666",
      "route_text_color": "000000"
    },
    {
      "route_id": 10,
      "agency_id": "LTC -2020 November",
      "route_short_name": 10,
      "route_long_name": "Route 10",
      "route_desc": "",
      "route_type": 3,
      "route_url": "",
      "route_color": "96BEFA",
      "route_text_color": "000000"
    },
    {
      "route_id": 102,
      "agency_id": "LTC -2020 November",
      "route_short_name": 102,
      "route_long_name": "Route 102",
      "route_desc": "",
      "route_type": 3,
      "route_url": "",
      "route_color": "C58AFF",
      "route_text_color": "000000"
    },
    {
      "route_id": 104,
      "agency_id": "LTC -2020 November",
      "route_short_name": 104,
      "route_long_name": "Route 104",
      "route_desc": "",
      "route_type": 3,
      "route_url": "",
      "route_color": "C58AFF",
      "route_text_color": "000000"
    },
    {
      "route_id": 106,
      "agency_id": "LTC -2020 November",
      "route_short_name": 106,
      "route_long_name": "Route 106",
      "route_desc": "",
      "route_type": 3,
      "route_url": "",
      "route_color": "C58AFF",
      "route_text_color": "000000"
    },
    {
      "route_id": 12,
      "agency_id": "LTC -2020 November",
      "route_short_name": 12,
      "route_long_name": "Route 12",
      "route_desc": "",
      "route_type": 3,
      "route_url": "",
      "route_color": "CA95FF",
      "route_text_color": "000000"
    },
    {
      "route_id": 13,
      "agency_id": "LTC -2020 November",
      "route_short_name": 13,
      "route_long_name": "Route 13",
      "route_desc": "",
      "route_type": 3,
      "route_url": "",
      "route_color": "927EC2",
      "route_text_color": "000000"
    },
    {
      "route_id": 15,
      "agency_id": "LTC -2020 November",
      "route_short_name": 15,
      "route_long_name": "Route 15",
      "route_desc": "",
      "route_type": 3,
      "route_url": "",
      "route_color": "00D5D5",
      "route_text_color": "000000"
    },
    {
      "route_id": 16,
      "agency_id": "LTC -2020 November",
      "route_short_name": 16,
      "route_long_name": "Route 16",
      "route_desc": "",
      "route_type": 3,
      "route_url": "",
      "route_color": "00AA55",
      "route_text_color": ""
    },
    {
      "route_id": 17,
      "agency_id": "LTC -2020 November",
      "route_short_name": 17,
      "route_long_name": "Route 17",
      "route_desc": "",
      "route_type": 3,
      "route_url": "",
      "route_color": "FF2828",
      "route_text_color": ""
    },
    {
      "route_id": 19,
      "agency_id": "LTC -2020 November",
      "route_short_name": 19,
      "route_long_name": "Route 19",
      "route_desc": "",
      "route_type": 3,
      "route_url": "",
      "route_color": "71D0FF",
      "route_text_color": ""
    },
    {
      "route_id": 20,
      "agency_id": "LTC -2020 November",
      "route_short_name": 20,
      "route_long_name": "Route 20",
      "route_desc": "",
      "route_type": 3,
      "route_url": "",
      "route_color": "58ABAB",
      "route_text_color": ""
    },
    {
      "route_id": 24,
      "agency_id": "LTC -2020 November",
      "route_short_name": 24,
      "route_long_name": "Route 24",
      "route_desc": "",
      "route_type": 3,
      "route_url": "",
      "route_color": "FF9BCD",
      "route_text_color": ""
    },
    {
      "route_id": 25,
      "agency_id": "LTC -2020 November",
      "route_short_name": 25,
      "route_long_name": "Route 25",
      "route_desc": "",
      "route_type": 3,
      "route_url": "",
      "route_color": "DFDF00",
      "route_text_color": ""
    },
    {
      "route_id": 27,
      "agency_id": "LTC -2020 November",
      "route_short_name": 27,
      "route_long_name": "Route 27",
      "route_desc": "",
      "route_type": 3,
      "route_url": "",
      "route_color": "FE9CA4",
      "route_text_color": ""
    },
    {
      "route_id": 28,
      "agency_id": "LTC -2020 November",
      "route_short_name": 28,
      "route_long_name": "Route 28",
      "route_desc": "",
      "route_type": 3,
      "route_url": "",
      "route_color": "5555FF",
      "route_text_color": ""
    },
    {
      "route_id": 30,
      "agency_id": "LTC -2020 November",
      "route_short_name": 30,
      "route_long_name": "Route 30",
      "route_desc": "",
      "route_type": 3,
      "route_url": "",
      "route_color": "CF2985",
      "route_text_color": ""
    },
    {
      "route_id": 31,
      "agency_id": "LTC -2020 November",
      "route_short_name": 31,
      "route_long_name": "Route 31",
      "route_desc": "",
      "route_type": 3,
      "route_url": "",
      "route_color": "00B700",
      "route_text_color": ""
    },
    {
      "route_id": 33,
      "agency_id": "LTC -2020 November",
      "route_short_name": 33,
      "route_long_name": "Route 33",
      "route_desc": "",
      "route_type": 3,
      "route_url": "",
      "route_color": "BB77FF",
      "route_text_color": ""
    },
    {
      "route_id": 34,
      "agency_id": "LTC -2020 November",
      "route_short_name": 34,
      "route_long_name": "Route 34",
      "route_desc": "",
      "route_type": 3,
      "route_url": "",
      "route_color": "5959FF",
      "route_text_color": ""
    },
    {
      "route_id": 35,
      "agency_id": "LTC -2020 November",
      "route_short_name": 35,
      "route_long_name": "Route 35",
      "route_desc": "",
      "route_type": 3,
      "route_url": "",
      "route_color": "DBC004",
      "route_text_color": ""
    },
    {
      "route_id": 36,
      "agency_id": "LTC -2020 November",
      "route_short_name": 36,
      "route_long_name": "Route 36",
      "route_desc": "",
      "route_type": 3,
      "route_url": "",
      "route_color": "B43D61",
      "route_text_color": ""
    },
    {
      "route_id": 37,
      "agency_id": "LTC -2020 November",
      "route_short_name": 37,
      "route_long_name": "Route 37",
      "route_desc": "",
      "route_type": 3,
      "route_url": "",
      "route_color": "0098E1",
      "route_text_color": ""
    },
    {
      "route_id": 90,
      "agency_id": "LTC -2020 November",
      "route_short_name": 90,
      "route_long_name": "Route 90",
      "route_desc": "",
      "route_type": 3,
      "route_url": "",
      "route_color": "FF8A15",
      "route_text_color": "000000"
    },
    {
      "route_id": 91,
      "agency_id": "LTC -2020 November",
      "route_short_name": 91,
      "route_long_name": "Route 91",
      "route_desc": "",
      "route_type": 3,
      "route_url": "",
      "route_color": "FF8000",
      "route_text_color": "000000"
    },
    {
      "route_id": 93,
      "agency_id": "LTC -2020 November",
      "route_short_name": 93,
      "route_long_name": "Route 93",
      "route_desc": "",
      "route_type": 3,
      "route_url": "",
      "route_color": "FF8000",
      "route_text_color": "000000"
    },
    {
      "route_id": 94,
      "agency_id": "LTC -2020 November",
      "route_short_name": 94,
      "route_long_name": "Route 94",
      "route_desc": "",
      "route_type": 3,
      "route_url": "",
      "route_color": "FF8000",
      "route_text_color": "000000"
    }
  ]`);
  export { routesDataJson };